### PR TITLE
use flowtype

### PR DESCRIPTION
**Pull request by joshwnj**
- added flowtype annotations
- added build and prepublish script

### CODE REVIEW

**Comment by joshwnj** [comment]
Hi @maxkrieger, I'm hoping to update this package to use flowtype annotations. Partly as a learning experience, but it will also reduce the risk of future breaks. 

If you have a moment could you please try upgrading your instance to use this branch, and let me know if it works? I don't want to push this without first checking for backwards-compatibility issues.

Thanks!

**Comment by maxkrieger** [comment]
I'm 50% sure this is just on my end and I'm probably building this wrong, but babel isn't liking your es6.
```
> style-attr@1.0.2 build /Users/xxx/project/node_modules/style-attr
> babel --out-dir lib src

SyntaxError: src/index.js: Unexpected token (16:19)
  14 |
  15 | */
> 16 | function parse (raw: string): {} {
     |                    ^
  17 |   var trim = function (s) { return s.trim(); };
  18 |   var obj = {};
  19 |
```

**Comment by joshwnj** [comment]
@maxkrieger could you please confirm whether you have the `.babelrc` file and have done an `npm install` to get the plugin it references?

**Comment by maxkrieger** [comment]
Ah, my mistake. Didn't copy all the files. Everything looks fine!

**Comment by joshwnj** [comment]
Cool thanks!

**Pull request merged**
